name: access_control
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  either_dart: ^1.0.0
  provider: ^6.1.5+1
  dio: ^5.9.0
  google_fonts: ^6.3.2
  flutter_feather_icons: ^2.0.0+1
  url_launcher: ^6.3.2
  sqflite: ^2.4.2
  path: ^1.9.1
  lottie: ^3.3.2
  widget_and_text_animator: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
